version: '3.9'
# 사용법 docker-compose.yml 참조

services:
  app:
    build: .
    depends_on:
      - redissession
      - rediscache
      - database
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REDIS_CACHE_HOST_NAME=rediscache
      - REDIS_SESSION_HOST_NAME=redissession
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=resell_platform
      - MYSQL_PASSWORD=resell1234
      - DB_SCHEMA=v_1