version: '3.9'

# Used for QA test too

services:
  rediscache:
    build: cache
    restart: always

  redissession:
    build: session
    restart: always

  database:
    build: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=resell_platform
      - MYSQL_PASSWORD=resell1234
      - DB_SCHEMA=resell_platform_webservice

networks:
  back-end:
    name: back-end
    driver: bridge