version: '3.9'

# 'Share Compose configurations' 사용법
# docker-compose up -d를 사용하면 docker-compose.override.yml이 암시적으로 같이 작동됨.
# docker-compose.yml 파일에 공통 구성 환경을 설정하고 override에는 암시적으로 실행됐으면 하는 환경을 설정 권장.
# docker-compose.prod는 override 파일이 아닌 자신이 공통 구성 환경과 같이 실행되길 원할 때 사용됨.
# 'docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d' 명령어를 사용하면 docker-compose와 prod만 실행됨.
# docker-compose.override는 비어 있을 수 있지만 파일 자체는 존재해야함. 'Share Compose configurations' 방식을 사용한다는 것을 명시하기 위함.

# convention : container_name/depends_on/image or build/restart/ports/environment

services:
  app:
    build: resell-platform-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - rediscache
      - redissession
      - database
    environment:
      - CACHE_HOSTNAME=rediscache
      - SESSION_HOSTNAME=redissession
      - DATABASE_HOSTNAME=database
      - SPRING_PROFILES_ACTIVE=jwt,real-db

networks:
  back-end:
    name: back-end
    driver: bridge

