version: '3.8'
# convention : container_name/depends_on/image or build/restart/ports/environment
services:
  rediscache:
    build: src/test/resources/testcontainers/cache
    restart: always

  redissession:
    build: src/test/resources/testcontainers/session
    restart: always

  database:
    build: src/test/resources/testcontainers/database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=resell_platform
      - MYSQL_PASSWORD=resell1234