version: '3.8'
# convention : container_name/depends_on/image or build/restart/ports/enviroment
services:
  rediscache:
    container_name: rediscache
    build: ./cache
    restart: always

  redissession:
    container_name: redissession
    build: ./session
    restart: always

  database:
    container_name: database
    build: ./database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=resell_platform
      - MYSQL_PASSWORD=resell1234

  app:
    depends_on:
      - session
      - cache
      - database
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REDIS_CACHE_HOST_NAME=rediscache
      - REDIS_SESSION_HOST_NAME=redissession
      - MYSQL_HOST=database:3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=resell_platform
      - MYSQL_PASSWORD=resell1234