version: '3.9'
# 사용법 docker-compose.yml 참조

services:
  app:
    build: .
    networks:
      - default
      - back-end
    restart: always
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: back-end

