version: '3.8'
# convention : container_name/depends_on/image or build/restart/ports/environment
services:
  rediscache:
    build: cache
    restart: always

  redissession:
    build: session
    restart: always

  database:
    build: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=resell_platform
      - MYSQL_PASSWORD=resell1234

  app:
    depends_on:
      - session
      - cache
      - database
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REDIS_CACHE_HOST_NAME=rediscache
      - REDIS_SESSION_HOST_NAME=redissession
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=resell_platform
      - MYSQL_PASSWORD=resell1234
      - DB_SCHEMA=v_1