version: '3.9'
# 사용법 docker-compose.yml 참조

services:
  rediscache:
    build: cache
    restart: always

  redissession:
    build: session
    restart: always
    
  app:

    depends_on:
      - rediscache
      - redissession
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REDIS_CACHE_HOST_NAME=rediscache
      - REDIS_SESSION_HOST_NAME=redissession

networks:
  default:
    external:
      name: back-end

