version: '3.9'

services:
  rediscache:
    build: cache
    restart: always
    ports:
      - "6379:6379"

  redissession:
    build: session
    restart: always
    ports:
      - "6380:6379"

  database:
    build: database
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=resell_platform
      - MYSQL_PASSWORD=resell1234
      - DB_SCHEMA=resell_platform_webservice
