# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - "main"
      - "devops/**"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: before-deploy, build image
      run: |
        docker build -t resell-platform-app .
        docker save resell-platform-app -o resell-platform-app.tar
        mkdir -p deploy
        mv resell-platform-app.tar deploy/resell-platform-app.tar
        chmod +x scripts/deploy.sh
        mv scripts/deploy.sh deploy/deploy.sh
        mv appspec.yml deploy/appspec.yml
        zip -r resell-platform deploy/*

#    - name: before_deploy
#      run: |
#        chmod +x scripts/deploy.sh
#        zip -r resell-platform * # 해당 디렉토리에 있는 모든 요소들을 zip으로 묶음
#        mkdir -p deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
#        mv resell-platform.zip deploy/resell-platform.zip

    - name: Upload to S3
      run: |
        aws s3 cp ./resell-platform.zip s3://resell-platform-image
      #        aws s3 cp ./deploy/resell-platform-app.zip s3://resell-platform-build

    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name resell-platform-webservice
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name resell-platform-webservice-group
        --s3-location bucket=resell-platform-image,bundleType=zip,key=resell-platform.zip
#        --s3-location bucket=resell-platform-build,bundleType=zip,key=resell-platform.zip